### ISSUE TITLE
http://gitbattle.com is down

### ISSUE THREAD

**Issue by mjkaufer** [jessepollak/githubbattle#14]
The site isn't coming up for me, and isup.me agrees.

:frowning:

**Comment by jessepollak** [comment]
Someone else registered the domain and now it's expired (and Dreamhost is asking $100 for it). I'm going to wait until it goes out of their system and then buy it (unless someone wants to help with the $100 fee :/).

**Comment by mjkaufer** [comment]
That sucks. Best of luck!

**Comment by anubiann00b** [comment]
Can we temporarily host this somewhere?

**Comment by jessepollak** [comment]
Putting this up at githubbattle.com.

**Comment by visnu** [comment]
Yay! So its fixed now! 👍
